"""Add ClausulasPuntos

Revision ID: 164d05e6af68
Revises: 6d0b6e153de3
Create Date: 2025-07-31 14:09:07.035941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164d05e6af68'
down_revision = '6d0b6e153de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clausulas_puntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fundamento_legal', sa.Text(), nullable=True),
    sa.Column('fundamento_doctrinario', sa.Text(), nullable=True),
    sa.Column('instrumentos_permitidos', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.Enum('GENERAL', 'OBLIGATORIA', 'SUGERIDA', 'PERSONALIZADA', name='tipoclausulaenum'), nullable=False),
    sa.Column('aplicacion', sa.Enum('DOCUMENTO', 'ACTA', 'AMBOS', name='tipoaplicacionclausulaenum'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clausulas_puntos')
    # ### end Alembic commands ###
