"""Fix: add nombre_bufete_o_razon_social

Revision ID: 3a9906ebb847
Revises: 
Create Date: 2025-07-15 21:24:55.753393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9906ebb847'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bufetes_juridicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_bufete_o_razon_social', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['nombre_bufete_o_razon_social'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bufetes_juridicos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('nombre_bufete_o_razon_social')

    # ### end Alembic commands ###
