"""lab: add TestPersona (NIT/DPI)

Revision ID: 6a14d8f75c10
Revises: 5640db94bd5b
Create Date: 2025-08-16 19:37:39.243296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a14d8f75c10'
down_revision = '5640db94bd5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nit', sa.String(length=32), nullable=False),
    sa.Column('dpi', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_personas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_personas_dpi'), ['dpi'], unique=True)
        batch_op.create_index(batch_op.f('ix_test_personas_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_personas_nit'), ['nit'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_personas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_personas_nit'))
        batch_op.drop_index(batch_op.f('ix_test_personas_name'))
        batch_op.drop_index(batch_op.f('ix_test_personas_dpi'))

    op.drop_table('test_personas')
    # ### end Alembic commands ###
