"""Add direccion and telefono to Notario

Revision ID: 870dc40cc02d
Revises: d9229c8ff333
Create Date: 2025-07-15 21:46:51.143178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870dc40cc02d'
down_revision = 'd9229c8ff333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notarios', schema=None) as batch_op:
        batch_op.drop_column('telefono')
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###
