"""test_personas: permitir CF repetido con nit_uq nullable unique

Revision ID: 88a638c63d39
Revises: 6a14d8f75c10
Create Date: 2025-08-18 18:59:44.696963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a638c63d39'
down_revision = '6a14d8f75c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nit_uq', sa.String(length=32), nullable=True))
        batch_op.drop_index(batch_op.f('ix_test_personas_nit'))
        batch_op.create_index(batch_op.f('ix_test_personas_nit'), ['nit'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_personas_nit_uq'), ['nit_uq'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_personas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_personas_nit_uq'))
        batch_op.drop_index(batch_op.f('ix_test_personas_nit'))
        batch_op.create_index(batch_op.f('ix_test_personas_nit'), ['nit'], unique=True)
        batch_op.drop_column('nit_uq')

    # ### end Alembic commands ###
