"""geo: countries/admin1/admin2/national_id_rules

Revision ID: b8af5570f2bc
Revises: 88a638c63d39
Create Date: 2025-08-18 20:15:51.356814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8af5570f2bc'
down_revision = '88a638c63d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso3')
    )
    with op.batch_alter_table('geo_countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geo_countries_iso2'), ['iso2'], unique=True)

    op.create_table('geo_admin1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type_name', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['geo_countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'code', name='uq_admin1_country_code')
    )
    op.create_table('national_id_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('id_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('regex', sa.String(length=200), nullable=True),
    sa.Column('dept_from_end', sa.Integer(), nullable=True),
    sa.Column('dept_len', sa.Integer(), nullable=True),
    sa.Column('muni_from_end', sa.Integer(), nullable=True),
    sa.Column('muni_len', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['geo_countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'id_type', name='uq_country_idtype')
    )
    op.create_table('geo_admin2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('admin1_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type_name', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['admin1_id'], ['geo_admin1.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['country_id'], ['geo_countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'admin1_id', 'code', name='uq_admin2_country_admin1_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geo_admin2')
    op.drop_table('national_id_rules')
    op.drop_table('geo_admin1')
    with op.batch_alter_table('geo_countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geo_countries_iso2'))

    op.drop_table('geo_countries')
    # ### end Alembic commands ###
