"""tabla intermedia Notario-Procurador

Revision ID: d35cc36a9dab
Revises: 
Create Date: 2025-07-28 20:26:50.080165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35cc36a9dab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notario_procurador_asociacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notario_id', sa.Integer(), nullable=False),
    sa.Column('procurador_id', sa.Integer(), nullable=False),
    sa.Column('bufete_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_reasignacion', sa.DateTime(), nullable=True),
    sa.Column('motivo_reasignacion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bufete_id'], ['bufetes_juridicos.id'], ),
    sa.ForeignKeyConstraint(['notario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['procurador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notario_procurador_asociacion')
    # ### end Alembic commands ###
