"""Refactor BufeteJuridico

Revision ID: d9229c8ff333
Revises: 3a9906ebb847
Create Date: 2025-07-15 21:37:16.023356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9229c8ff333'
down_revision = '3a9906ebb847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bufetes_juridicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('app_copyright', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nombre_aplicacion', sa.String(length=255), nullable=True))
        batch_op.drop_column('nombre')
        batch_op.drop_column('correo_electronico')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bufetes_juridicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo_electronico', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_column('nombre_aplicacion')
        batch_op.drop_column('app_copyright')
        batch_op.drop_column('email')
        batch_op.drop_column('nit')

    # ### end Alembic commands ###
